# Root Project Information
sonar.projectKey=autocheck
sonar.projectName=autocheck
sonar.host.url=http://localhost:9000
sonar.token=sqp_c2d6a617a28b86db622292c1f27d510e5d81233a

# Define comma-separated paths to all source and test roots
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src,frontend/tests

# Monorepo Glob Inclusions
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.config.*,**/*.setup.*,**/models/**,**/main.ts,**/app.config.ts,**/app.routes.ts,**/app.component.ts,frontend/src/app/features/**,frontend/src/app/core/guards/**,frontend/src/app/core/interceptors/**,backend/src/controllers/**,backend/src/middlewares/**

# Pass a comma-separated list of all generated coverage reports
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info